services:
  monolito-asesorias:
    image: dcalle2026/monolito-asesorias:latest
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGODB_URI=${MONGODB_URI}
    restart: always

  microservicio-proyectos:
    image: dcalle2026/microservicio-proyectos:latest
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MONGODB_URI=${MONGODB_URI}
    restart: always
